# Generated by Django 4.0 on 2022-01-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSe005930',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('contents', models.TextField()),
                ('registered_date', models.DateTimeField()),
                ('hits', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'board_se005930',
                'managed': False,
            },
        ),
    ]
