# Generated by Django 4.0 on 2022-01-04 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSe005930',
            fields=[
                ('pid', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='board.boardse005930')),
                ('uid', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'comment_se005930',
                'managed': False,
            },
        ),
    ]
