# Generated by Django 4.0 on 2022-01-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_commentse005930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120)),
                ('contents', models.TextField()),
                ('registered_date', models.DateTimeField()),
                ('hits', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uid', models.IntegerField()),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
                ('comments', models.TextField()),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='commentse005930',
            name='pid',
        ),
        migrations.DeleteModel(
            name='BoardSe005930',
        ),
        migrations.DeleteModel(
            name='CommentSe005930',
        ),
    ]
